---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: zipkin
  name: zipkin
spec:
  type: NodePort
  ports:
    - name: http
      port: 9411
      targetPort: 9411
      nodePort: 30081
  selector:
    project: piggymetrics
    tier: infrastructure
    app: zipkin
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: zipkin
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: piggymetrics
                  key: config_service_password
          image: mariase/piggymetrics-zipkin-new
          name: zipkin
          ports:
            - containerPort: 9411
          resources: {}
      restartPolicy: Always
status: {}