---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  type: NodePort
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 30082
  selector:
    project: piggymetrics
    tier: infrastructure
    app: registry
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: registry
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: config_pwd
#              valueFrom:
#                secretKeyRef:
#                  name: piggymetrics
#                  key: config_service_password
          image: mariase/piggymetrics-registry
          name: registry
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}