---
apiVersion: v1
kind: Service
metadata:
  name: statistics-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
  name: statistics-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: statistics-mongodb
    spec:
      containers:
        - env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: piggymetrics
                  key: mongodb_password
          ports:
            - containerPort: 27017
          image: mariase/piggymetrics-mongodb
          name: statistics-mongodb
          resources: {}
      restartPolicy: Always
status: {}